---
name: 'GitHub App Authenticate'
description: |
  A GitHub Actions custom JavaScript action that authenticates a GitHub App and generates an installation token to use in authenticated GitHub API requests.
inputs:
  app-id:
    description: 'The ID of the GitHub App (not the installation ID)'
    required: true
  installation-id:
    description: |
      Installation ID for the specified GitHub App.
      If not provided, this action will attempt to look up
      the installation ID using the repository
      where this action is used.
    required: false
  list-installs:
    default: false
    required: false
  org:
    description: |
      The organization to authenticate for.
      If not provided, this action will use the owner of the repo that
      used this action.
    required: false
  private-key:
    description: 'PEM encoded RSA private key for the GitHub App'
    required: true
outputs:
  installation-id:
    description: 'Installation ID used to generate token'
  installed-orgs:
    description: 'List of orgs the app is installed on'
  token:
    description: 'GitHub App Installation Token'
runs:
  using: 'node16'
  main: 'dist/index.js'
